apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: cert-exporter-psp
  name: calicoctl
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    env:
    - name: ETCD_ENDPOINTS
      value: https://127.0.0.1:2379
    - name: ETCD_CA_CERT_FILE
      value: /etc/kubernetes/ssl/etcd/etcd-ca.pem
    - name: ETCD_CERT_FILE
      value: /etc/kubernetes/ssl/etcd/etcd.pem
    - name: ETCD_KEY_FILE
      value: /etc/kubernetes/ssl/etcd/etcd-key.pem
    image: quay.io/calico/ctl:v3.5.1
    imagePullPolicy: IfNotPresent
    name: calicoctl
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl/etcd
      name: etcd-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl/etcd
      type: ""
    name: etcd-certs
  - name: default-token
    secret:
      defaultMode: 420
      secretName: default-token-qsnqp
