apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    env:
    - name: ETCD_ENDPOINTS
      value: https://127.0.0.1:2379
    - name: ETCD_CA_CERT_FILE
      value: /etc/kubernetes/ssl/etcd/client-ca.pem
    - name: ETCD_CERT_FILE
      value: /etc/kubernetes/ssl/etcd/client-crt.pem
    - name: ETCD_KEY_FILE
      value: /etc/kubernetes/ssl/etcd/client-key.pem
    image: quay.io/calico/ctl:v3.5.1
    imagePullPolicy: IfNotPresent
    name: calicoctl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl/etcd
      name: etcd-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token
      readOnly: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl/etcd
      type: ""
    name: etcd-certs
  - name: default-token
    secret:
      defaultMode: 420
      secretName: default-token-lkvrx
