apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  namespace: kube-system
  labels:
    app: iperf2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name:  netshoot
        image: nicolaka/netshoot
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
