apiVersion: v1
kind: Pod
metadata:
  name: giantswarm-troubleshooting
spec:
  hostNetwork: true
  nodeName: 2krpk-worker-00000m
  containers:
  - name: giantswarm-troubleshooting
    image: calvix/dev
    command:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
