apiVersion: v1
kind: Service
metadata:
  name: sise
  labels:
    app: sise
spec:
  ports:
    - name: sise
      port: 80
      targetPort: 9876
  selector:
    app: sise
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sise-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: mhausenblas/simpleservice:0.3.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
